BATCH_SIZE = 32
ALPHA = 1

REPLAY_MEMORY_SIZE = 1_000_000
MIN_REPLAY_MEMORY_SIZE = 1000
EXPONENT_A = 0.7
EXPONENT_B = lambda eps: 1 - eps
OFFSET = 0.1

TRAIN_EVERY_K_STEPS = 2
UPDATE_STABLE_MODEL_EVERY_K_STEPS = 100
STABLE_MODEL_TAU = 1

DISCOUNT = 0.995

EPSILON = 1
SCALE_EPSILON = 0.999
MIN_EPSILON = 0.001

# Those are just evaluation parameters. They don't actually effect the training
EVALUATE_EVERY = 50
EVALUATE_GAMES = 10
