BATCH_SIZE = 64
ALPHA = 0.01

REPLAY_MEMORY_SIZE = 1_000_000
MIN_REPLAY_MEMORY_SIZE = 50000
EXPONENT_A = 0.7
EXPONENT_B = lambda eps: 1 - eps
OFFSET = 0.1

TRAIN_EVERY_K_STEPS = 8
UPDATE_STABLE_MODEL_EVERY_K_STEPS = 400
STABLE_MODEL_TAU = 1

DISCOUNT = 1.

EPSILON = 1
SCALE_EPSILON = 0.9998
MIN_EPSILON = 0.005

# Those are just evaluation parameters. They don't actually effect the training
EVALUATE_EVERY = 100
EVALUATE_GAMES = 30
